CLIENT_DISCONNECT =     37

CLIENT_HEARTBEAT =      52

-- new toontown specific login message, adds last logged in, and if child account has parent acount
CLIENT_LOGIN_TOONTOWN =      125
CLIENT_LOGIN_TOONTOWN_RESP = 126

CLIENT_DISCONNECT_GENERIC =       1
CLIENT_DISCONNECT_RELOGIN =       100
CLIENT_DISCONNECT_ACCOUNT_ERROR = 122
CLIENT_DISCONNECT_BAD_VERSION =   125

DATABASE_OBJECT_TYPE_ACCOUNT = 1

CLIENTAGENT_EJECT = 3004
