CLIENT_GET_AVATARS =         3
CLIENT_GET_AVATARS_RESP =    5
CLIENT_CREATE_AVATAR =       6
CLIENT_CREATE_AVATAR_RESP =  7

CLIENT_OBJECT_UPDATE_FIELD = 24

CLIENT_DISCONNECT =          37

CLIENT_DELETE_AVATAR_RESP =  5

CLIENT_HEARTBEAT =           52

CLIENT_ADD_INTEREST =        97
CLIENT_REMOVE_INTEREST =     99

-- new toontown specific login message, adds last logged in, and if child account has parent acount
CLIENT_LOGIN_TOONTOWN =      125
CLIENT_LOGIN_TOONTOWN_RESP = 126

CLIENT_DISCONNECT_GENERIC =            1
CLIENT_DISCONNECT_RELOGIN =            100
CLIENT_DISCONNECT_OVERSIZED_DATAGRAM = 106
CLIENT_DISCONNECT_ACCOUNT_ERROR =      122
CLIENT_DISCONNECT_BAD_VERSION =        125

DATABASE_OBJECT_TYPE_ACCOUNT = 1
DATABASE_OBJECT_TYPE_TOON =    2

CLIENTAGENT_EJECT = 3004
